import debruijn

# 示例读取数据
reads = [
    "GGGGGGGGGGGGGGGGGGGGGTAGCATCTATTGCAGCTCAAGAATTGTGACCTTATAACAGTTTTAACCCCAATTGGGGAAAAAAGGAAAA", 
    "ATAACAGTTTTAACCCCAATTGGGGAAAAAAGGAAAATTTTTTCCTTAAGGAATTTTAATTAAAAAATTAAAATTGGAACCAAAATTGGTTG", 
    "ATTAAAAAATTAAAATTGGAACCAAAATTGGTTGGAAGGTTTTTTCCCCTTAAGGTTTTAACCCCAAAAGGTTGGTTAATTTTTTAATTAAAAAAAATTGGAAAATTTTCCCCAAAAAAGGGGTTAACCGGTTGGAACCAATTTTTTAAAATTTTCCCCAATTCCCCTTAATTTTTTTTTTAAGGAAAACCCTGAAGGATAATAAAGGAAAATACCACCCCTTCA", 
    "GTTGGTTAAAACCAAGGTTAAAATTAAAAAATTAATTTTAAGGAATTCCTTTTTTAAAAGGAAAAAAGGGGTTAACCCCAATTTTGACAATA"
]
k = 23

graph = debruijn.de_bruijn_graph(reads, k)

assembled_sequence = debruijn.assemble_sequence(graph)
print(f"Assembled sequence: {assembled_sequence}")

debruijn.output_gml(graph, "debruijn_graph.gml")
print("GML file has been saved as 'debruijn_graph.gml'.")
